### ISSUE TITLE
Аккумулятор не поддерживается

### ISSUE THREAD

**Issue by BoxaS** [mnh-jansson/open-battery-information#26]
Добрый день. Имел 4 заблокированных, 3 разблокировал благодаря вашей работе. Один BL 1830 пишет, что присутствует, но не поддерживается. Могли бы вы внести его что бы он поддерживался программой. Если нужны какие нибудь данные по нем, свяжитесь со мной. ROM ID 0C 09 12 64 22 04 04 B8
Battery message 50 31 60 53 13 68 00 00 C5 C1 71 55 B2 62 01 13 F0 D0 8E 3C 6F ED  00 41 E1 02 0E B2 00 92 01

**Comment by mnh-jansson** [comment]
F0513 are currently not supported. I'm not sure if the solution will ever reach this open-source version at this point. There are too many people claiming this work as their own and selling it which has made me reconsider how i will distribute this information.
