### ISSUE TITLE
Does makita LIPW014 not support?

### ISSUE THREAD

**Issue by MayDayCom** [mnh-jansson/open-battery-information#27]
![20241224_105534](https://github.com/user-attachments/assets/6a336e88-67d2-4eba-9025-c5869a4ce0ee)
![20241224_105523](https://github.com/user-attachments/assets/0e7199fe-6429-4047-aea4-f50686abd576)
![20241224_105515](https://github.com/user-attachments/assets/262e5e90-a87c-47e8-a5bf-fa8127d30bd8)

Does makita LIPW014 not support?

![Error_](https://github.com/user-attachments/assets/df22c695-ad03-4202-83a5-37a9ade95dbb)

**Comment by ch9511** [comment]
This message popup when wires not connected to battery. Check if all wires connected correct, battery voltage not lower than 19v also you can try NEWAS and TH connect together when you try to read battery.

**Comment by MayDayCom** [comment]
Thank you. I will try again.

**Comment by MayDayCom** [comment]
Connection successful. Thank you.

**Comment by mnh-jansson** [comment]
Closing for now, feel free to reopen if the issue was not resolved.
