### ISSUE TITLE
hello, thank you very much for all makita lxt users.

### ISSUE THREAD

**Issue by Bennypro66** [mnh-jansson/open-battery-information#4]
hello, my name is benoit.  I am French and I communicate with a translator.  I am an admirer of this work that you have done.  it is a success.  the bl1850b and 60b are now repairable in a clean way thanks to you 💪 I have in my possession a bl4080f card which has no faults but at times is refused by the xgt charger.  and a bl4040 card which is faulty and flashing.  I am ready to donate it to you if you are looking for some for your experiments.   thank you again for this beautiful work 👌
I'll leave you my email if you want to communicate for the delivery of the cards
nicolas.makita.66@gmail.com
Sincerely
Nicolas
![20240714_144351](https://github.com/user-attachments/assets/2dfc2e64-aae7-4c3f-9f26-f2cdc54ba45f)

**Comment by mnh-jansson** [comment]
Thank you! I'll close this as resolved as we have been in contact. 

Added contact email in README. 825b7f4932701540788cd46890b675e4eca3a1ed
